[Docker] Update the tag of the built and published docker images
buildwithgrove/path pull request #34
Opened 2024-09-25 22:50 UTC by Olshansk

Two main changes:
- Always tag the latest image with `latest`
- Use a shortened version of the `sha`

Where images are stored: https://github.com/buildwithgrove/path/pkgs/container/path

2024-09-25 23:40 UTC, HebertCL requested changes
Just a NIT on what seems an unnecessary duplicated line

2024-09-25 23:40 UTC, HebertCL commented on .github/workflows/main-build.yml
> +            type=sha,format=short,suffix=-rc
This line seems to contain the same parameters as previous one, just different order. Is that intended?

2024-09-30 19:34 UTC, HebertCL approved these changes
LGTM

2024-09-30 23:30 UTC, Olshansk commented
![Screenshot 2024-09-30 at 4 30 13 PM](https://github.com/user-attachments/assets/afe106a7-7a49-4d14-99d5-589b9f43205c)

2024-09-30 23:30 UTC, merged