Create initial setup and workflow for docusaurus
buildwithgrove/path pull request #55
Opened 2024-10-31 18:10 UTC by HebertCL

# TL;DR

Create initial Docusaurus setup to handle static page documentation.

## Summary

This PR handles the following components:

- Docusaurus folder structure and basic page for Path static page documentation.
- GitHub Actions workflow to handle the deployment of documentation static page.

## TODO

- Setup GitHub Pages to mirror `poktroll` configuration.
- Setup DNS recordset for the page (name TBD).

2024-11-07 19:30 UTC, Olshansk requested changes
@HebertCL Thanks for kicking this off!

1. PTAL at admonitions. It's the best way to add notes in the future: https://docusaurus.io/docs/markdown-features/admonitions

2. I updated the main README to use ☝️ as a reference.

3. Can you add an empty `develop` and `operate` section similar to what we have in dev.poktroll.com.

It took me a little while to figure it out the first time, but just copy-pasting the pattern we have there should be enough.

**Why now?** If you set it up/configure it, it'll incentivize the rest of the team to actually add docs :)

<img width="1668" alt="Screenshot 2024-11-07 at 2 08 33 PM" src="https://github.com/user-attachments/assets/7a773dc4-c438-4db4-8853-e050cf21bd65">

2024-11-07 19:30 UTC, Olshansk commented on docusaurus/README.md
> +# Website
Is this something you added or was it a default?

I'm thinking we just update it to use `make docusaurus_start` from the main Makefile. Wdyt?

2024-11-08 17:40 UTC, HebertCL commented
> 3. Can you add an empty `develop` and `operate` section similar to what we have in dev.poktroll.com.

I've taken care of this and confirm that the validation is passing and building is working correctly in local. I've went ahead and request re-review.

2024-11-11 17:07 UTC, Olshansk approved these changes
Let's :shipit: 

Thanks @HebertCL!

2024-11-11 17:43 UTC, merged